# fly.toml app configuration file generated for whisper-service
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "whisper-service"
primary_region = "dfw"

[build]

[env]
  WHISPER_MODEL_SIZE = "base"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
